version: '3'
services:
  agent:
    image: "datadog/agent:6.10.0"
    env_file:
      - ../apikey.env
    environment:
      - DD_APM_ENABLED=true
      - DD_LOG_LEVEL=debug
    ports:
      - "8126:8126"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro 
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /root/agentconf.d:/conf.d:ro
  web:
    build: ..
    command: flask run --port=5000 --host=0.0.0.0
    environment:
      - FLASK_APP=first.py
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"
    depends_on:
      - agent
  