version: '3'
services:
  agent:
    image: "datadog/agent:6.10.0"
    labels:
      com.datadoghq.ad.check_names: '["disk"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"mount_point_blacklist": ["/host/proc/sys/fs/binfmt_misc"]}]'
    env_file:
      - ../apikey.env
    environment:
      - DD_APM_ENABLED=true
    ports:
      - "8126:8126"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro 
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
  web:
    build: ..
    command: flask run --port=5000 --host=0.0.0.0
    labels:
      com.datadoghq.ad.check_names: '["disk", "ntp"]'
      com.datadoghq.ad.init_configs: '[{}, {}]'
      com.datadoghq.ad.instances: '[{"mount_point_blacklist": ["/host/proc/sys/fs/binfmt_misc"], "excluded_filesystems": ["/host/proc/sys/fs/binfmt_misc"]}, {"host": "pool.ntp.org"}]'
    environment:
      - FLASK_APP=first.py
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"
    depends_on:
      - agent
  